language: perl
perl:
  - "5.20"
  - "5.22"
addons:
  postgresql: 9.6
services:
  - postgresql
env:
  global:
    - TEST_ONLINE=postgresql://postgres@/cs_test
install:
  - cpanm -n --installdeps .
before_script:
  - psql -U postgres -c 'create database cs_test;'
script:
  - prove -lv
after_script:
  - cat log/development.log
sudo: false
dist: trusty
notifications:
  email: false
