- name: pg repo source
  shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

- name: apt keys
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: pg
  apt: name=postgresql state=latest update_cache=yes

- name: pg user
  shell: psql -c "create role {{pg_cs_user}} login password '{{pg_cs_pass}}'"
  become: yes
  become_user: postgres
  register: r
  failed_when: r.rc > 1
  changed_when: "'CREATE ROLE' in r.stdout"

- name: pg db
  shell: createdb -O {{pg_cs_user}} {{pg_cs_db}}
  become: yes
  become_user: postgres
  register: r
  failed_when: r.rc > 1
  changed_when: r.rc == 0

- name: pg config
  template:
    src=pg_cs.conf.j2 dest=/etc/postgresql/11/main/conf.d/cs.conf
  notify:
    - restart postgresql

- name: pg_hba config
  lineinfile:
    path: /etc/postgresql/11/main/pg_hba.conf
    insertafter: '^# IPv4 local connections:'
    regexp: '^host\tcs'
    line: "host\tcs\tcs\t0.0.0.0/0\tmd5"
  notify:
    - restart postgresql
