- name: docker
  include_tasks: docker.yml

- name: user
  user:
    name: "{{ cs_user }}"
    groups: docker
    append: yes
    state: present

- name: system requirements
  apt:
    name:
      - atop
      - make
      - sudo
      - rsync
    state: latest
    update_cache: yes

- name: node_exporter
  include_tasks:
    file: node_exporter.yml
    apply:
      tags: node_exporter
  tags: node_exporter

- name: pull cs image
  docker_image:
    name: "{{ cs_docker_image }}"
    source: pull
    force_source: yes
  tags: update
