- name: systemd config
  template: src=cs.web.service.j2 dest=/etc/systemd/system/cs.web.service
  notify:
    - reload systemd
  tags: update

- name: nginx repo source
  shell: echo "deb http://nginx.org/packages/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/ $(lsb_release -cs) nginx" > /etc/apt/sources.list.d/nginx.list

- name: apt keys
  apt_key:
    url: https://nginx.ru/keys/nginx_signing.key

- name: nginx
  apt: name=nginx state=latest update_cache=yes

- name: nginx cache catalog
  file:
    path: /var/cache/nginx/cs
    state: directory
    owner: nginx
    group: root
    mode: 0700

- name: nginx config
  template: src=cs.nginx.conf.j2 dest=/etc/nginx/conf.d/cs.conf
  notify:
    - restart nginx
  tags: update
