- hosts: cs
  roles:
    - common

- hosts: cs-db
  roles:
    - db
  tags:
    - db

- hosts: cs-master
  roles:
    - manager
    - web
    - watcher

- hosts: cs-flags
  roles:
    - flags

- hosts: cs-checker, cs-master
  roles:
    - checkers
