- hosts: cs
  roles:
    - common

- hosts: db
  roles:
    - db
  tags:
    - db

- hosts: master
  roles:
    - manager
    - web
    - watcher

- hosts: flags
  roles:
    - flags

- hosts: checkers, master
  roles:
    - checkers
