- hosts: flags
  tasks:
    - name: stop web flags
      docker_container:
        name: cs_web_flags
        state: stopped

- hosts: checkers
  tasks:
    - name: stop checkers
      docker_container:
        name: "cs_checker_worker_{{ item }}"
        state: stopped
      with_sequence: count={{ cs_worker_instance }}

- hosts: master
  tasks:
    - name: stop manager
      docker_container:
        name: cs_manager
        state: stopped

    - name: stop default worker
      docker_container:
        name: cs_default_worker
        state: stopped

    - name: stop watcher
      docker_container:
        name: cs_watcher
        state: stopped

    - name: stop web
      docker_container:
        name: cs_web
        state: stopped
