- hosts: cs-master
  tasks:
    - name: stop manager
      systemd: name=cs.manager state=stopped
    - name: stop worker
      systemd: name=cs.worker-default state=stopped
    - name: stop web
      systemd: name=cs.web state=stopped
    - name: stop watcher
      systemd: name=cs.watcher state=stopped

- hosts: cs-flags
  tasks:
    - name: stop flags
      systemd: name="cs.flags@{{item}}" state=stopped
      with_sequence: count={{cs_flags_instance}}

- hosts: cs-checker
  tasks:
    - name: stop checkers
      systemd: name=cs.worker-checkers state=stopped
